shopcatalog/productsapp/urls.py
from django.contrib import admin
from django.urls import path

from .views import ProductsListView, ProductsCrateView


app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='main'),
    path('<int:pk>', ProductsListView.as_view(), name='main'),
    path('add/', ProductsCrateView.as_view(), name='create'),
]

shopcatalog/shopcatalog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productsapp.urls')),
]

shopcatalog/hitcount/models.py
from django.db import models


class HitCount(models.Model):
    path = models.CharField(max_length=512, primary_key=True)
    hits = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.path}  ({self.hits})'

shopcatalog/productsapp/models.py
from django.contrib.sites.managers import CurrentSiteManager
from django.contrib.sites.models import Site
from django.db import models
from django.db.models import Manager
from django.utils.translation import gettext_lazy


class Supplier(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    objects = Manager()
    on_site = CurrentSiteManager('site')

    def __str__(self):
        return self.name


class Products(models.Model):
    class Meta:
        ordering = ['name']

    class Unit(models.TextChoices):
        PIECES = 'PC', gettext_lazy('Штук')
        KILOGRAM = 'KG', gettext_lazy('Килограм')

    name = models.CharField(max_length=64)
    entrance_data = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    unit = models.CharField(max_length=2, choices=Unit.choices, default=Unit.PIECES)
    supplier_name = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    category = models.ManyToManyField(ProductCategory, verbose_name='Категория')
    site = models.ManyToManyField(Site)
    objects = Manager()
    on_site = CurrentSiteManager('site')

shopcatalog/hitcount/views.py
from django.shortcuts import render

# Create your views here.

shopcatalog/productsapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .models import Products


class ProductsListView(ListView):
    model = Products
    template_name = 'productsapp/products_list.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        # queryset = super().get_queryset().prefetch_related('category').all()
        if 'pk' in self.kwargs:
            queryset = Products.on_site.filter(category__id=self.kwargs['pk']).prefetch_related('category').all()
        else:
            queryset = Products.on_site.prefetch_related('category').all()
        return queryset


class ProductsCrateView(CreateView):
    model = Products
    fields = ['name', 'price', 'unit', 'supplier_name', 'category']
    template_name = 'productsapp/products_create.html'

    def get_success_url(self):
        return reverse_lazy('products:main')

shopcatalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div style='width: 1100px; margin-left: auto; margin-right: auto'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'products:main' %}">Главная(все)</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% for category in categories %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:main' category.id %}">
                            {{ category.name }}
                        </a>
                    </li>
                    {% endfor %}}
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link" href="#">Link</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item dropdown">-->
<!--                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"-->
<!--                           data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                            Dropdown-->
<!--                        </a>-->
<!--                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--                            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--                            <li>-->
<!--                                <hr class="dropdown-divider">-->
<!--                            </li>-->
<!--                            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--                    </li>-->
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

shopcatalog/templates/productsapp/products_create.html
{% extends "base.html" %}
{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="сохранить">
</form>
{% endblock %}

shopcatalog/templates/productsapp/products_list.html
{% extends "base.html" %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Категория</th>
      <th scope="col">Поставщик</th>
      <th scope="col">ед.изм.</th>
      <th scope="col">Цена</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
      <tr>
        <th scope="row">{{ product.name|upper }}</th>
        <th scope="row">
          {% for cat in product.category.all %}
          {{ cat }}
          {% endfor %}
        </th>
        <td>{{product.supplier_name.name}}</td>
        <td>{{ product.get_unit_display }}</td>
        <td>{{ product.price }}</td>
      </tr>
    {% endfor %}
    <tr>
        <td colspan="3"></td>
        <td>
          <a href="{% url 'products:create' %}">
            <button type="button" class="btn btn-primary">Добавить товар</button>
          </a>
        </td>
      </tr>
  </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}